name: dental-clinic-mvp

channels:
  - defaults

dependencies:
  - python
  - pip
  - pip:
      - streamlit
      - pymongo
      - python-dotenv
      - pandas
      - plotly
      - pytest
      - pydantic
